//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsApplication.Models
{
    using ProductsApplication.ViewModels;
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Category { get; set; }
        public int ManufacturerID { get; set; }
        public int SupplierID { get; set; }
        public double Price { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Supplier Supplier { get; set; }

        public Product()
        {

        }

        public Product(ProductViewModel productViewModel)
        {
            Name = productViewModel.Name;
            Description = productViewModel.Description;
            ManufacturerID = productViewModel.ManufacturerID;
            SupplierID = productViewModel.SupplierID;
            Price = productViewModel.Price;
        }
    }
}
